{
 "title": "Day 10 Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP probe success / latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://example.com\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_duration_seconds{instance=\"https://example.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk free %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 * (\n    node_filesystem_avail_bytes{fstyle!~\"tmpfs|overly\"}\n    /\n\n    node_filesystem_size_bytes{fstyle!~\"tmpfs|overlay\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage host ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvaiable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}