apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: demo
data:
  APP_ENV: "dev"
  APP_MESSAGE: "Hello from ConfigMap"
  app.properties: |
    feature.flag=true
    welcome.message=Hello from mounted ConfigMap file
